global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cloudnordsp-control-plane'
    static_configs:
      - targets: ['control-plane:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'cloudnordsp-nodes'
    static_configs:
      - targets: ['node-1:8081', 'node-2:8081', 'node-3:8081']
    metrics_path: '/metrics'
    scrape_interval: 10s
