apiVersion: v1
kind: ConfigMap
metadata:
  name: control-plane-config
  namespace: cloudnordsp
data:
  config.yaml: |
    debug: false
    api:
      address: ":8080"
      read_timeout: 30s
      write_timeout: 30s
      idle_timeout: 120s
      max_header_bytes: 1048576
      enable_cors: true
      enable_metrics: true
      rate_limit_rps: 100
      rate_limit_burst: 200
    database:
      type: postgres
      host: postgres
      port: 5432
      database: cloudnordsp
      username: cloudnordsp
      password: changeme
      ssl_mode: disable
      max_open_conns: 25
      max_idle_conns: 5
      max_lifetime: 5m
    node:
      update_interval: 30s
      health_check_interval: 10s
      max_nodes: 100
      node_timeout: 30s
      retry_attempts: 3
      retry_delay: 5s
    proxy:
      enable_tcp_proxy: true
      enable_udp_proxy: true
      tcp_timeout: 30s
      udp_timeout: 10s
      max_connections: 10000
      buffer_size: 4096
      enable_af_xdp: true
      xdp_interface: eth0
      xdp_queue_id: 0
    monitoring:
      enable_prometheus: true
      metrics_path: /metrics
      enable_logging: true
      log_level: info
      log_format: json
      enable_tracing: false
      trace_endpoint: ""
      sample_rate: 0.1
    security:
      enable_tls: false
      tls_cert_file: ""
      tls_key_file: ""
      enable_jwt: true
      jwt_secret: "your-secret-key-change-this-in-production"
      jwt_expiry: 24h
      enable_rbac: true
      enable_rate_limit: true
      rate_limit_rps: 100
      rate_limit_burst: 200
      enable_ip_whitelist: false
      allowed_ips: []

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-plane
  namespace: cloudnordsp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: control-plane
  template:
    metadata:
      labels:
        app: control-plane
    spec:
      containers:
      - name: control-plane
        image: cloudnordsp/control-plane:latest
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_HOST
          value: postgres
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_NAME
          value: cloudnordsp
        - name: DATABASE_USER
          value: cloudnordsp
        - name: DATABASE_PASSWORD
          value: changeme
        volumeMounts:
        - name: config
          mountPath: /root/config.yaml
          subPath: config.yaml
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: config
        configMap:
          name: control-plane-config

---
apiVersion: v1
kind: Service
metadata:
  name: control-plane
  namespace: cloudnordsp
spec:
  selector:
    app: control-plane
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
